### ISSUE TITLE
RA8876

### ISSUE THREAD

**Issue by Diablo550** [sumotoy/RA8876#1]
Hi,

I am experimenting with this chip on my pcb.

I would like to see your code, 

but the files are empty :(

Nick

**Comment by sumotoy** [comment]
I push code only when I got a stable and 90% working library...

**Comment by Diablo550** [comment]
I made some PCBs for the 8877 chip.
I will start with the SPI 8875 driver.
did you find any major software differences for the 8876 Vs 8875 ?

**Comment by sumotoy** [comment]
> > did you find any major software differences for the 8876 Vs 8875 ?

Hardware is completely different and because memory is external there's many timing issues between configurations.
I got the RA8875 work outside it's speed range after long time, had to rewrote lib many times but now with RA8876/77 everithing changes with new chip so I'm currently under timings tuning.
With hardware accellerated chip is never easy, I have to wait the job is done inside RA and (again) the hardware ready pin is not reliable at all so SPI request is the only option but because the many possible hardware configurations and massive display area of the new chip it's not as easy.
Of course the legacy code provided by Raio works but really slow, this is why I'm building a library from scratch.
Did you using the 512Mb buffer?

**Comment by Diablo550** [comment]
I have been looking at this for the last few days, 
I am trying to start my 8877 code.
but I am a novice programmer in C :(
My first RA8877board has 32Mb x16 SDRAM with SPI and Char Rom support.
My other RA8877 board has 32Mx32 SDRAM, but no pins for SPI port and no char rom pins
My primary board is a STM32F7 with separate SDRAM

**Comment by Diablo550** [comment]
I got my 16bit PCB sort of working... based on picture viewer...
but its not in 24bit colour.. maybe tomorrow
I hope it still works after I run in 24bit mode.

Yes, I can see how it needs work...

**Comment by Diablo550** [comment]
Are you running 32bit ram or 16bit ?
still not working :(

**Comment by Diablo550** [comment]
It runs !
I have 24bit RGB on 1366 x 768 graphics, with 32M x 16bit SDRAM
but I cannot print more than 1 text char 
:(

**Comment by sumotoy** [comment]
I'm still working on the next release of RA8875 but I can tell you I prefere working at 16bit, first because tiny microcontrollers doesn't like 24bit (better 32bit but it's a waste of data) for code alignement reasons caused by internal registers. For example, I can assign uint16_t or uint32_t but NOT uint24_t.

**Comment by Diablo550** [comment]
I guess you are discussing the color depth of 16bits. being more simple to use than the 24bit color.
My biggest question was if the RA8877 could run in 24bit mode on an 18" panel.
Now that 24bit color works, we can happily run in 16bit color mode.
